/**
 * Action types constants
 *
 * @type {Object}
 */
const ActionTypes = {
    INITIALIZE: 'INITIALIZE',

    ADD_BOARD: 'ADD_BOARD',
    ADD_COLUMN: 'ADD_COLUMN',
    ADD_CARD: 'ADD_CARD',

    DELETE_BOARD: 'DELETE_BOARD',
    DELETE_COLUMN: 'DELETE_COLUMN',
    DELETE_CARD: 'DELETE_CARD',

    SHOW_CONFIRM_MODAL: 'SHOW_CONFIRM_MODAL',
    SHOW_BOARD_ENTRY_MODAL: 'SHOW_BOARD_ENTRY_MODAL',
    SHOW_COLUMN_ENTRY_MODAL: 'SHOW_COLUMN_ENTRY_MODAL',
    SHOW_CARD_ENTRY_MODAL: 'SHOW_CARD_ENTRY_MODAL',
    HIDE_MODAL: 'HIDE_MODAL',
    REMOVE_MODAL: 'REMOVE_MODAL'
};

export default ActionTypes;
